package br.ce.wcaquino.servicos;

import java.util.Date;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;

import org.junit.Assert;
import org.junit.Test;

import br.ce.wcaquino.entidades.Filme;
import br.ce.wcaquino.entidades.Locacao;
import br.ce.wcaquino.entidades.Usuario;
import br.ce.wcaquino.exceptions.FilmeSemEstoqueException;
import br.ce.wcaquino.exceptions.LocadoraException;
import br.ce.wcaquino.utils.DataUtils;

public class LocacaoServiceTest {
	
	@Test
	public void test() throws LocadoraException, FilmeSemEstoqueException {
		// Arrange
		LocacaoService service = new LocacaoService();
		Usuario usuario = new Usuario("Igor");
		Filme filme = new Filme("Harry Potter", 2, 2.50);
		
		// Act
		Locacao locacao = service.alugarFilme(usuario, filme);
		
		// Assert
		assertThat(locacao.getValor(), is(2.50));
		assertTrue(DataUtils.isMesmaData(locacao.getDataLocacao(), new Date()));
		Assert.assertTrue(DataUtils.isMesmaData(locacao.getDataRetorno(), DataUtils.obterDataComDiferencaDias(1)));
		
	}
	
	@Test
	public void testLocacao_filmeSemEstoque_2() throws LocadoraException {
		//cenario
		LocacaoService service = new LocacaoService();
		Usuario usuario = new Usuario("Usuario 1");
		Filme filme = new Filme("Filme 2", 2, 4.0);
		
		//acao
		try {
			service.alugarFilme(usuario, filme);
			Assert.fail("Deveria ter lancado uma excecao"); // Sempre colocar um Assert.fail porque se n√£o cair na exception da classe, vai cair nessa assertion de erro
		} catch (Exception e) {
			assertThat(e.getMessage(), is("Filme sem estoque"));
		}
	}

}
